experiment: 01171847_PanopLi_hypersim001008_booming-bow
seed: 467
save_epoch: 1
sanity_steps: -1
max_epoch: 34
val_check_percent: 1.0
val_check_interval: 1
resume: null
subsample_frames: 1
segment_grouping_mode: argmax_conf
semantic_weight_mode: softmax
late_semantic_optimization: 4
use_symmetric_ce: false
probabilistic_ce_mode: TTAConf
use_feature_regularization: false
lambda_feat: 0.04
ce_alpha: 0.85
ce_beta: 0.15
lr: 0.0005
lambda_segment: 0.5
lambda_semantics: 0.1
lambda_instances: 0.1
lambda_rgb: 1
lambda_dist_reg: 0
weight_class_0: 0
weight_decay: 1.0e-08
stop_semantic_grad: true
use_mlp_for_semantics: true
decay_step:
- 16
- 32
- 48
decay_gamma: 0.5
warmup_epochs: 0
warmup_multiplier: 1.0
batch_size: 2048
max_rays_instances: 1024
max_rays_segments: 1024
batch_size_contrastive: 1
batch_size_segments: 32
max_instances: 20
chunk: 2048
chunk_segment: 16384
num_workers: 8
logger: wandb
overfit: false
min_grid_dim: 128
max_grid_dim: 192
lambda_tv_density: 0.1
lambda_tv_semantics: 0.02
lambda_tv_appearance: 0.01
bbox_aabb_reset_epochs:
- 2
- 4
- 8
grid_upscale_epochs:
- 2
- 4
- 8
- 16
- 20
instance_optimization_epoch: 8
segment_optimization_epoch: 18
perturb: 1.0
noise_std: 1.0
decay_noise: 20000
max_depth: 5
reweight_fg: false
dataset_class: panopli
dataset_root: data/hypersim/ai_001_008/
image_dim:
- 320
- 320
visualized_indices: null
wandb_main: true
suffix: ''
